name: consumer

on:
  push:
    paths:
      - '**/consumer.py'
    branches:
      - main  

jobs:
  editorconfig:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Run EditorConfig check
      uses: actions/checkout@v2
    
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Run linters
      uses: wearerequired/lint-action@v2
         