name: producer

on:
  push:
    paths:
      - '**/producer.py'
    branches:
      - main  

jobs:
  editorconfig:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Run EditorConfig check
      run: editorconfig-checker
    
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Run Linter check
      run: pylint

